# Databricks notebook source
# MAGIC %md
# MAGIC # 91 — Parity check
# MAGIC Compares the gold tables against baseline CSVs (generated by the
# MAGIC reference DuckDB/pandas implementation) in a UC Volume.

# COMMAND ----------

dbutils.widgets.text("catalog", "retail_banking_dev")
dbutils.widgets.text("run_date", "")
dbutils.widgets.text("lookback_months", "12")
dbutils.widgets.text("parity_volume", "")

try:
    import retail_banking  # noqa: F401
except ImportError:
    import sys
    root = dbutils.notebook.entry_point.getDbutils().notebook() \
        .getContext().notebookPath().get().rsplit("/", 2)[0]
    sys.path.append(f"/Workspace{root}/src")

from retail_banking.config import PipelineConfig
from retail_banking.logging_utils import log_step
from retail_banking.parity import compare_gold_outputs

# COMMAND ----------

cfg = PipelineConfig.from_widgets(dbutils)
step = "91_PARITY_CHECK"
log_step(spark, step, "START", audit_table=cfg.audit_table)

volume = dbutils.widgets.get("parity_volume") or cfg.parity_volume
tables = ["customer_segments", "transaction_analytics",
          "customer_risk_scores", "customer_master_profile"]

expected = {t: (spark.read.option("header", "true")
                .option("inferSchema", "true")
                .csv(f"{volume}/{t}.csv"))
            for t in tables}
actual = {t: spark.table(cfg.gold_table(t)) for t in tables}

report = compare_gold_outputs(actual, expected)
report.print_report()

if not report.passed:
    log_step(spark, step, "ERROR", msg="Parity check failed",
             audit_table=cfg.audit_table)
    raise ValueError("Parity check failed - see report above")

log_step(spark, step, "SUCCESS", rowcount=len(report.checks),
         audit_table=cfg.audit_table)
